### ISSUE TITLE
redirectTo should persist route and query params

### ISSUE THREAD

**Issue by briananderson1222** [angular/vladivostok#86]
Using the redirect strategy that I've seen floating around.

```js
{ path: '', redirectTo: 'home', terminal: true },
{ path: 'home', component: HomeComponent }
```

Loading the url `/;test=test?test=test` should persist both route and query params during redirect.

Currently neither the route params or query params are persisted.

**Comment by findjonmos** [comment]
Add a forward slash in front of redirectTo: 'home' - so that it looks as below...
`
{ path: '', redirectTo: '/home', terminal: true },
`

If they are going to remove / from all route paths should it not be done for redirectTo also...otherwise this is really confusing.

Routing is actually broken if you don't add this slash for redirectTo - no links will work!

**Comment by brandonroberts** [comment]
@findjonmos the reason it still exists for redirects is that you can redirect relative to where you are, or absolute from the root.

```js
{ path: '', redirectTo: '/home', terminal: true },
{ path: 'home', component: HomeComponent },
{ path: 'old', redirectTo: 'new' },
{ path: 'new', component: NewComponent }
```

**Comment by briananderson1222** [comment]
Am I wrong to assume that route params should also persist during a redirect?

**Comment by brandonroberts** [comment]
@briananderson1222 yes, they should

**Comment by robwormald** [comment]
This issue was moved to angular/angular#9494
